steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/test-app:$BUILD_ID"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-app:$BUILD_ID"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "tasks-app",
        "--image",
        "gcr.io/$PROJECT_ID/test-app:$BUILD_ID",
        "--region",
        "southamerica-west1",
        "--allow-unauthenticated",
      ]
